# This is a TOML file. The syntax is important.

# This sets up a redirect/rewrite rule.
[[redirects]]
  # A more specific path for our image uploads
  from = "/api/storage/*"

  # The REAL, full destination path to your storage bucket's objects
  # The :splat will now only contain the file name and query params
  to = "https://firebasestorage.googleapis.com/v0/b/herbal-pansar.appspot.com/o/:splat"

  # A status of 200 makes this a "rewrite" or "proxy".
  status = 200
