# This is a TOML file. The syntax is important.

# This sets up a redirect/rewrite rule.
[[redirects]]
  # A new path for our upload proxy
  from = "/api/upload"

  # The CORRECT destination server endpoint for Firebase Storage uploads
  to = "https://firebasestorage.googleapis.com/v0/b/herbal-pansar.appspot.com/o"

  # A status of 200 makes this a "rewrite" or "proxy"
  status = 200
  
  # IMPORTANT: This ensures query parameters (like "?uploadType=media&name=...") are passed through
  force = true
